// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/lobby.proto
// Protobuf Java Version: 4.28.3

package com.example.lobby;

public final class Lobby {
  public Lobby() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Lobby.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JoinRoomRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JoinRoomRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string player_id = 2;</code>
     * @return The playerId.
     */
    java.lang.String getPlayerId();
    /**
     * <code>string player_id = 2;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();
  }
  /**
   * Protobuf type {@code JoinRoomRequest}
   */
  public static final class JoinRoomRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:JoinRoomRequest)
      JoinRoomRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        JoinRoomRequest.class.getName());
    }
    // Use JoinRoomRequest.newBuilder() to construct.
    private JoinRoomRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JoinRoomRequest() {
      playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.lobby.Lobby.internal_static_JoinRoomRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.lobby.Lobby.internal_static_JoinRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.lobby.Lobby.JoinRoomRequest.class, com.example.lobby.Lobby.JoinRoomRequest.Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playerId_ = "";
    /**
     * <code>string player_id = 2;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string player_id = 2;</code>
     * @return The bytes for playerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, playerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.lobby.Lobby.JoinRoomRequest)) {
        return super.equals(obj);
      }
      com.example.lobby.Lobby.JoinRoomRequest other = (com.example.lobby.Lobby.JoinRoomRequest) obj;

      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.lobby.Lobby.JoinRoomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.lobby.Lobby.JoinRoomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.JoinRoomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.lobby.Lobby.JoinRoomRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JoinRoomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JoinRoomRequest)
        com.example.lobby.Lobby.JoinRoomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.lobby.Lobby.internal_static_JoinRoomRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.lobby.Lobby.internal_static_JoinRoomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.lobby.Lobby.JoinRoomRequest.class, com.example.lobby.Lobby.JoinRoomRequest.Builder.class);
      }

      // Construct using com.example.lobby.Lobby.JoinRoomRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.lobby.Lobby.internal_static_JoinRoomRequest_descriptor;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.JoinRoomRequest getDefaultInstanceForType() {
        return com.example.lobby.Lobby.JoinRoomRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.lobby.Lobby.JoinRoomRequest build() {
        com.example.lobby.Lobby.JoinRoomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.JoinRoomRequest buildPartial() {
        com.example.lobby.Lobby.JoinRoomRequest result = new com.example.lobby.Lobby.JoinRoomRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.lobby.Lobby.JoinRoomRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.lobby.Lobby.JoinRoomRequest) {
          return mergeFrom((com.example.lobby.Lobby.JoinRoomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.lobby.Lobby.JoinRoomRequest other) {
        if (other == com.example.lobby.Lobby.JoinRoomRequest.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object playerId_ = "";
      /**
       * <code>string player_id = 2;</code>
       * @return The playerId.
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player_id = 2;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_id = 2;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 2;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:JoinRoomRequest)
    }

    // @@protoc_insertion_point(class_scope:JoinRoomRequest)
    private static final com.example.lobby.Lobby.JoinRoomRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.lobby.Lobby.JoinRoomRequest();
    }

    public static com.example.lobby.Lobby.JoinRoomRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinRoomRequest>
        PARSER = new com.google.protobuf.AbstractParser<JoinRoomRequest>() {
      @java.lang.Override
      public JoinRoomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JoinRoomRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinRoomRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.lobby.Lobby.JoinRoomRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreamJoinRoomResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StreamJoinRoomResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    java.util.List<com.example.lobby.Lobby.Player> 
        getOtherPlayersList();
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    com.example.lobby.Lobby.Player getOtherPlayers(int index);
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    int getOtherPlayersCount();
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    java.util.List<? extends com.example.lobby.Lobby.PlayerOrBuilder> 
        getOtherPlayersOrBuilderList();
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    com.example.lobby.Lobby.PlayerOrBuilder getOtherPlayersOrBuilder(
        int index);

    /**
     * <code>.Player me = 3;</code>
     * @return Whether the me field is set.
     */
    boolean hasMe();
    /**
     * <code>.Player me = 3;</code>
     * @return The me.
     */
    com.example.lobby.Lobby.Player getMe();
    /**
     * <code>.Player me = 3;</code>
     */
    com.example.lobby.Lobby.PlayerOrBuilder getMeOrBuilder();

    /**
     * <code>int32 max_players = 4;</code>
     * @return The maxPlayers.
     */
    int getMaxPlayers();
  }
  /**
   * Protobuf type {@code StreamJoinRoomResponse}
   */
  public static final class StreamJoinRoomResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StreamJoinRoomResponse)
      StreamJoinRoomResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        StreamJoinRoomResponse.class.getName());
    }
    // Use StreamJoinRoomResponse.newBuilder() to construct.
    private StreamJoinRoomResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StreamJoinRoomResponse() {
      otherPlayers_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.lobby.Lobby.internal_static_StreamJoinRoomResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.lobby.Lobby.internal_static_StreamJoinRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.lobby.Lobby.StreamJoinRoomResponse.class, com.example.lobby.Lobby.StreamJoinRoomResponse.Builder.class);
    }

    private int bitField0_;
    public static final int OTHER_PLAYERS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.example.lobby.Lobby.Player> otherPlayers_;
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.lobby.Lobby.Player> getOtherPlayersList() {
      return otherPlayers_;
    }
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.lobby.Lobby.PlayerOrBuilder> 
        getOtherPlayersOrBuilderList() {
      return otherPlayers_;
    }
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    @java.lang.Override
    public int getOtherPlayersCount() {
      return otherPlayers_.size();
    }
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    @java.lang.Override
    public com.example.lobby.Lobby.Player getOtherPlayers(int index) {
      return otherPlayers_.get(index);
    }
    /**
     * <code>repeated .Player other_players = 2;</code>
     */
    @java.lang.Override
    public com.example.lobby.Lobby.PlayerOrBuilder getOtherPlayersOrBuilder(
        int index) {
      return otherPlayers_.get(index);
    }

    public static final int ME_FIELD_NUMBER = 3;
    private com.example.lobby.Lobby.Player me_;
    /**
     * <code>.Player me = 3;</code>
     * @return Whether the me field is set.
     */
    @java.lang.Override
    public boolean hasMe() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Player me = 3;</code>
     * @return The me.
     */
    @java.lang.Override
    public com.example.lobby.Lobby.Player getMe() {
      return me_ == null ? com.example.lobby.Lobby.Player.getDefaultInstance() : me_;
    }
    /**
     * <code>.Player me = 3;</code>
     */
    @java.lang.Override
    public com.example.lobby.Lobby.PlayerOrBuilder getMeOrBuilder() {
      return me_ == null ? com.example.lobby.Lobby.Player.getDefaultInstance() : me_;
    }

    public static final int MAX_PLAYERS_FIELD_NUMBER = 4;
    private int maxPlayers_ = 0;
    /**
     * <code>int32 max_players = 4;</code>
     * @return The maxPlayers.
     */
    @java.lang.Override
    public int getMaxPlayers() {
      return maxPlayers_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < otherPlayers_.size(); i++) {
        output.writeMessage(2, otherPlayers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getMe());
      }
      if (maxPlayers_ != 0) {
        output.writeInt32(4, maxPlayers_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < otherPlayers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, otherPlayers_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMe());
      }
      if (maxPlayers_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, maxPlayers_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.lobby.Lobby.StreamJoinRoomResponse)) {
        return super.equals(obj);
      }
      com.example.lobby.Lobby.StreamJoinRoomResponse other = (com.example.lobby.Lobby.StreamJoinRoomResponse) obj;

      if (!getOtherPlayersList()
          .equals(other.getOtherPlayersList())) return false;
      if (hasMe() != other.hasMe()) return false;
      if (hasMe()) {
        if (!getMe()
            .equals(other.getMe())) return false;
      }
      if (getMaxPlayers()
          != other.getMaxPlayers()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOtherPlayersCount() > 0) {
        hash = (37 * hash) + OTHER_PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getOtherPlayersList().hashCode();
      }
      if (hasMe()) {
        hash = (37 * hash) + ME_FIELD_NUMBER;
        hash = (53 * hash) + getMe().hashCode();
      }
      hash = (37 * hash) + MAX_PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxPlayers();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.StreamJoinRoomResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.lobby.Lobby.StreamJoinRoomResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StreamJoinRoomResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StreamJoinRoomResponse)
        com.example.lobby.Lobby.StreamJoinRoomResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.lobby.Lobby.internal_static_StreamJoinRoomResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.lobby.Lobby.internal_static_StreamJoinRoomResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.lobby.Lobby.StreamJoinRoomResponse.class, com.example.lobby.Lobby.StreamJoinRoomResponse.Builder.class);
      }

      // Construct using com.example.lobby.Lobby.StreamJoinRoomResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getOtherPlayersFieldBuilder();
          getMeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (otherPlayersBuilder_ == null) {
          otherPlayers_ = java.util.Collections.emptyList();
        } else {
          otherPlayers_ = null;
          otherPlayersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        me_ = null;
        if (meBuilder_ != null) {
          meBuilder_.dispose();
          meBuilder_ = null;
        }
        maxPlayers_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.lobby.Lobby.internal_static_StreamJoinRoomResponse_descriptor;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.StreamJoinRoomResponse getDefaultInstanceForType() {
        return com.example.lobby.Lobby.StreamJoinRoomResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.lobby.Lobby.StreamJoinRoomResponse build() {
        com.example.lobby.Lobby.StreamJoinRoomResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.StreamJoinRoomResponse buildPartial() {
        com.example.lobby.Lobby.StreamJoinRoomResponse result = new com.example.lobby.Lobby.StreamJoinRoomResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.lobby.Lobby.StreamJoinRoomResponse result) {
        if (otherPlayersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            otherPlayers_ = java.util.Collections.unmodifiableList(otherPlayers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.otherPlayers_ = otherPlayers_;
        } else {
          result.otherPlayers_ = otherPlayersBuilder_.build();
        }
      }

      private void buildPartial0(com.example.lobby.Lobby.StreamJoinRoomResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.me_ = meBuilder_ == null
              ? me_
              : meBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.maxPlayers_ = maxPlayers_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.lobby.Lobby.StreamJoinRoomResponse) {
          return mergeFrom((com.example.lobby.Lobby.StreamJoinRoomResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.lobby.Lobby.StreamJoinRoomResponse other) {
        if (other == com.example.lobby.Lobby.StreamJoinRoomResponse.getDefaultInstance()) return this;
        if (otherPlayersBuilder_ == null) {
          if (!other.otherPlayers_.isEmpty()) {
            if (otherPlayers_.isEmpty()) {
              otherPlayers_ = other.otherPlayers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOtherPlayersIsMutable();
              otherPlayers_.addAll(other.otherPlayers_);
            }
            onChanged();
          }
        } else {
          if (!other.otherPlayers_.isEmpty()) {
            if (otherPlayersBuilder_.isEmpty()) {
              otherPlayersBuilder_.dispose();
              otherPlayersBuilder_ = null;
              otherPlayers_ = other.otherPlayers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              otherPlayersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOtherPlayersFieldBuilder() : null;
            } else {
              otherPlayersBuilder_.addAllMessages(other.otherPlayers_);
            }
          }
        }
        if (other.hasMe()) {
          mergeMe(other.getMe());
        }
        if (other.getMaxPlayers() != 0) {
          setMaxPlayers(other.getMaxPlayers());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                com.example.lobby.Lobby.Player m =
                    input.readMessage(
                        com.example.lobby.Lobby.Player.parser(),
                        extensionRegistry);
                if (otherPlayersBuilder_ == null) {
                  ensureOtherPlayersIsMutable();
                  otherPlayers_.add(m);
                } else {
                  otherPlayersBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getMeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 32: {
                maxPlayers_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.lobby.Lobby.Player> otherPlayers_ =
        java.util.Collections.emptyList();
      private void ensureOtherPlayersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          otherPlayers_ = new java.util.ArrayList<com.example.lobby.Lobby.Player>(otherPlayers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder> otherPlayersBuilder_;

      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public java.util.List<com.example.lobby.Lobby.Player> getOtherPlayersList() {
        if (otherPlayersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otherPlayers_);
        } else {
          return otherPlayersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public int getOtherPlayersCount() {
        if (otherPlayersBuilder_ == null) {
          return otherPlayers_.size();
        } else {
          return otherPlayersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public com.example.lobby.Lobby.Player getOtherPlayers(int index) {
        if (otherPlayersBuilder_ == null) {
          return otherPlayers_.get(index);
        } else {
          return otherPlayersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder setOtherPlayers(
          int index, com.example.lobby.Lobby.Player value) {
        if (otherPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherPlayersIsMutable();
          otherPlayers_.set(index, value);
          onChanged();
        } else {
          otherPlayersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder setOtherPlayers(
          int index, com.example.lobby.Lobby.Player.Builder builderForValue) {
        if (otherPlayersBuilder_ == null) {
          ensureOtherPlayersIsMutable();
          otherPlayers_.set(index, builderForValue.build());
          onChanged();
        } else {
          otherPlayersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder addOtherPlayers(com.example.lobby.Lobby.Player value) {
        if (otherPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherPlayersIsMutable();
          otherPlayers_.add(value);
          onChanged();
        } else {
          otherPlayersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder addOtherPlayers(
          int index, com.example.lobby.Lobby.Player value) {
        if (otherPlayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherPlayersIsMutable();
          otherPlayers_.add(index, value);
          onChanged();
        } else {
          otherPlayersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder addOtherPlayers(
          com.example.lobby.Lobby.Player.Builder builderForValue) {
        if (otherPlayersBuilder_ == null) {
          ensureOtherPlayersIsMutable();
          otherPlayers_.add(builderForValue.build());
          onChanged();
        } else {
          otherPlayersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder addOtherPlayers(
          int index, com.example.lobby.Lobby.Player.Builder builderForValue) {
        if (otherPlayersBuilder_ == null) {
          ensureOtherPlayersIsMutable();
          otherPlayers_.add(index, builderForValue.build());
          onChanged();
        } else {
          otherPlayersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder addAllOtherPlayers(
          java.lang.Iterable<? extends com.example.lobby.Lobby.Player> values) {
        if (otherPlayersBuilder_ == null) {
          ensureOtherPlayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, otherPlayers_);
          onChanged();
        } else {
          otherPlayersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder clearOtherPlayers() {
        if (otherPlayersBuilder_ == null) {
          otherPlayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          otherPlayersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public Builder removeOtherPlayers(int index) {
        if (otherPlayersBuilder_ == null) {
          ensureOtherPlayersIsMutable();
          otherPlayers_.remove(index);
          onChanged();
        } else {
          otherPlayersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public com.example.lobby.Lobby.Player.Builder getOtherPlayersBuilder(
          int index) {
        return getOtherPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public com.example.lobby.Lobby.PlayerOrBuilder getOtherPlayersOrBuilder(
          int index) {
        if (otherPlayersBuilder_ == null) {
          return otherPlayers_.get(index);  } else {
          return otherPlayersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public java.util.List<? extends com.example.lobby.Lobby.PlayerOrBuilder> 
           getOtherPlayersOrBuilderList() {
        if (otherPlayersBuilder_ != null) {
          return otherPlayersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otherPlayers_);
        }
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public com.example.lobby.Lobby.Player.Builder addOtherPlayersBuilder() {
        return getOtherPlayersFieldBuilder().addBuilder(
            com.example.lobby.Lobby.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public com.example.lobby.Lobby.Player.Builder addOtherPlayersBuilder(
          int index) {
        return getOtherPlayersFieldBuilder().addBuilder(
            index, com.example.lobby.Lobby.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .Player other_players = 2;</code>
       */
      public java.util.List<com.example.lobby.Lobby.Player.Builder> 
           getOtherPlayersBuilderList() {
        return getOtherPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder> 
          getOtherPlayersFieldBuilder() {
        if (otherPlayersBuilder_ == null) {
          otherPlayersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder>(
                  otherPlayers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          otherPlayers_ = null;
        }
        return otherPlayersBuilder_;
      }

      private com.example.lobby.Lobby.Player me_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder> meBuilder_;
      /**
       * <code>.Player me = 3;</code>
       * @return Whether the me field is set.
       */
      public boolean hasMe() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.Player me = 3;</code>
       * @return The me.
       */
      public com.example.lobby.Lobby.Player getMe() {
        if (meBuilder_ == null) {
          return me_ == null ? com.example.lobby.Lobby.Player.getDefaultInstance() : me_;
        } else {
          return meBuilder_.getMessage();
        }
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public Builder setMe(com.example.lobby.Lobby.Player value) {
        if (meBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          me_ = value;
        } else {
          meBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public Builder setMe(
          com.example.lobby.Lobby.Player.Builder builderForValue) {
        if (meBuilder_ == null) {
          me_ = builderForValue.build();
        } else {
          meBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public Builder mergeMe(com.example.lobby.Lobby.Player value) {
        if (meBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            me_ != null &&
            me_ != com.example.lobby.Lobby.Player.getDefaultInstance()) {
            getMeBuilder().mergeFrom(value);
          } else {
            me_ = value;
          }
        } else {
          meBuilder_.mergeFrom(value);
        }
        if (me_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public Builder clearMe() {
        bitField0_ = (bitField0_ & ~0x00000002);
        me_ = null;
        if (meBuilder_ != null) {
          meBuilder_.dispose();
          meBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public com.example.lobby.Lobby.Player.Builder getMeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMeFieldBuilder().getBuilder();
      }
      /**
       * <code>.Player me = 3;</code>
       */
      public com.example.lobby.Lobby.PlayerOrBuilder getMeOrBuilder() {
        if (meBuilder_ != null) {
          return meBuilder_.getMessageOrBuilder();
        } else {
          return me_ == null ?
              com.example.lobby.Lobby.Player.getDefaultInstance() : me_;
        }
      }
      /**
       * <code>.Player me = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder> 
          getMeFieldBuilder() {
        if (meBuilder_ == null) {
          meBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.lobby.Lobby.Player, com.example.lobby.Lobby.Player.Builder, com.example.lobby.Lobby.PlayerOrBuilder>(
                  getMe(),
                  getParentForChildren(),
                  isClean());
          me_ = null;
        }
        return meBuilder_;
      }

      private int maxPlayers_ ;
      /**
       * <code>int32 max_players = 4;</code>
       * @return The maxPlayers.
       */
      @java.lang.Override
      public int getMaxPlayers() {
        return maxPlayers_;
      }
      /**
       * <code>int32 max_players = 4;</code>
       * @param value The maxPlayers to set.
       * @return This builder for chaining.
       */
      public Builder setMaxPlayers(int value) {

        maxPlayers_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max_players = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxPlayers() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxPlayers_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StreamJoinRoomResponse)
    }

    // @@protoc_insertion_point(class_scope:StreamJoinRoomResponse)
    private static final com.example.lobby.Lobby.StreamJoinRoomResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.lobby.Lobby.StreamJoinRoomResponse();
    }

    public static com.example.lobby.Lobby.StreamJoinRoomResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamJoinRoomResponse>
        PARSER = new com.google.protobuf.AbstractParser<StreamJoinRoomResponse>() {
      @java.lang.Override
      public StreamJoinRoomResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StreamJoinRoomResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamJoinRoomResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.lobby.Lobby.StreamJoinRoomResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string player_id = 1;</code>
     * @return The playerId.
     */
    java.lang.String getPlayerId();
    /**
     * <code>string player_id = 1;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();
  }
  /**
   * Protobuf type {@code Player}
   */
  public static final class Player extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Player)
      PlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Player.class.getName());
    }
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Player() {
      playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.lobby.Lobby.internal_static_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.lobby.Lobby.internal_static_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.lobby.Lobby.Player.class, com.example.lobby.Lobby.Player.Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playerId_ = "";
    /**
     * <code>string player_id = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string player_id = 1;</code>
     * @return The bytes for playerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, playerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.lobby.Lobby.Player)) {
        return super.equals(obj);
      }
      com.example.lobby.Lobby.Player other = (com.example.lobby.Lobby.Player) obj;

      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.lobby.Lobby.Player parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.lobby.Lobby.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.lobby.Lobby.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.lobby.Lobby.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.lobby.Lobby.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.lobby.Lobby.Player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Player)
        com.example.lobby.Lobby.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.lobby.Lobby.internal_static_Player_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.lobby.Lobby.internal_static_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.lobby.Lobby.Player.class, com.example.lobby.Lobby.Player.Builder.class);
      }

      // Construct using com.example.lobby.Lobby.Player.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.lobby.Lobby.internal_static_Player_descriptor;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.Player getDefaultInstanceForType() {
        return com.example.lobby.Lobby.Player.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.lobby.Lobby.Player build() {
        com.example.lobby.Lobby.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.lobby.Lobby.Player buildPartial() {
        com.example.lobby.Lobby.Player result = new com.example.lobby.Lobby.Player(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.lobby.Lobby.Player result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.lobby.Lobby.Player) {
          return mergeFrom((com.example.lobby.Lobby.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.lobby.Lobby.Player other) {
        if (other == com.example.lobby.Lobby.Player.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object playerId_ = "";
      /**
       * <code>string player_id = 1;</code>
       * @return The playerId.
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player_id = 1;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_id = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string player_id = 1;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Player)
    }

    // @@protoc_insertion_point(class_scope:Player)
    private static final com.example.lobby.Lobby.Player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.lobby.Lobby.Player();
    }

    public static com.example.lobby.Lobby.Player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player>
        PARSER = new com.google.protobuf.AbstractParser<Player>() {
      @java.lang.Override
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.lobby.Lobby.Player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinRoomRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JoinRoomRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamJoinRoomResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StreamJoinRoomResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/lobby.proto\"$\n\017JoinRoom" +
      "Request\022\021\n\tplayer_id\030\002 \001(\t\"b\n\026StreamJoin" +
      "RoomResponse\022\036\n\rother_players\030\002 \003(\0132\007.Pl" +
      "ayer\022\023\n\002me\030\003 \001(\0132\007.Player\022\023\n\013max_players" +
      "\030\004 \001(\005\"\033\n\006Player\022\021\n\tplayer_id\030\001 \001(\t2G\n\014L" +
      "obbyService\0227\n\010JoinRoom\022\020.JoinRoomReques" +
      "t\032\027.StreamJoinRoomResponse0\001B3\n\021com.exam" +
      "ple.lobbyZ\036github.com/luisg6/common/lobb" +
      "yb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JoinRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JoinRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_JoinRoomRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_StreamJoinRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StreamJoinRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StreamJoinRoomResponse_descriptor,
        new java.lang.String[] { "OtherPlayers", "Me", "MaxPlayers", });
    internal_static_Player_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Player_descriptor,
        new java.lang.String[] { "PlayerId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
